# Generated by Django 4.1.4 on 2022-12-17 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='Title')),
                ('Summary', models.TextField(verbose_name='Summary')),
                ('Price', models.CharField(max_length=8, verbose_name='Price')),
                ('Author', models.CharField(max_length=50, verbose_name='Author')),
                ('page_count', models.BigIntegerField(verbose_name='Page Count')),
                ('cover', models.ImageField(upload_to='cover', verbose_name='Cover')),
                ('Information', models.TextField(blank=True, null=True, verbose_name='Information')),
                ('Created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('Updated', models.DateTimeField(auto_now=True, verbose_name='Edited')),
                ('exist', models.CharField(choices=[('have', 'have'), ('in_order', 'in_order'), ('finish', 'finish')], default='have', max_length=8, verbose_name='exist')),
                ('Category', models.ManyToManyField(to='pages.category', verbose_name='Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
    ]
