# Generated by Django 4.1.4 on 2023-01-05 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='hitsfilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timecreated', models.DateTimeField(auto_now_add=True, verbose_name='timeview')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ipaddress', verbose_name='ip_address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.book', verbose_name='book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='pages.hitsfilter', to='pages.ipaddress', verbose_name='views'),
        ),
    ]
