# Generated by Django 4.1.4 on 2023-01-06 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0006_hitsfilter_book_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Price',
            field=models.BigIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='seller'),
        ),
    ]
