# Generated by Django 4.1.4 on 2023-01-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_book_price_alter_book_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price_with_discount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='discount price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='cover/', verbose_name='Cover'),
        ),
    ]
