# Generated by Django 4.1.4 on 2023-01-26 18:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_book_price_with_discount_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Summary',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
