# Generated by Django 4.1.4 on 2023-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customeuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='role'),
        ),
    ]
