# Generated by Django 4.1.4 on 2023-01-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_about_us_options_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='instagram',
            field=models.CharField(blank=True, max_length=70, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='linkdin',
            field=models.CharField(blank=True, max_length=70, verbose_name='Linkdin'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='phone',
            field=models.CharField(default='09015738669', max_length=11, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='telegram',
            field=models.CharField(blank=True, max_length=70, verbose_name='telegram'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=70, verbose_name='whatsapp'),
        ),
    ]
