# Generated by Django 4.1.4 on 2023-02-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_alter_about_us_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='address',
            field=models.CharField(default='address', max_length=50, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='email',
            field=models.EmailField(default='email', max_length=254, verbose_name='email'),
        ),
    ]
