# Generated by Django 4.1.4 on 2023-02-06 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.orderinfo', verbose_name='info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderinfo', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
