# Generated by Django 4.1.4 on 2023-02-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_info_alter_orderinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='info',
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
