# Generated by Django 4.1.4 on 2023-02-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.orderinfo', verbose_name='info'),
            preserve_default=False,
        ),
    ]
